interface eth0 {
    send ia-pd 0;
};

id-assoc pd 0 {
    prefix-interface eth1 {
        sla-id 1;
        sla-len 8; 
    };
    prefix-interface eth2 {
        sla-id 2;
        sla-len 8; 
    };
};