# File: r2/etc/racoon/racoon.conf

# Indichiamo dove trovare le password
path pre_shared_key "/etc/racoon/psk.txt";

# FASE 1: IKE_SA (Autenticazione tra i due router)
remote 100.60.0.2 {
    exchange_mode main;    # Modalità di scambio standard
    proposal {
        encryption_algorithm 3des;      # Cifratura del canale IKE
        hash_algorithm md5;             # Integrità del canale IKE
        authentication_method pre_shared_key; # Metodo: password condivisa
        dh_group 2;                     # Gruppo Diffie-Hellman per lo scambio chiavi
    }
}

# FASE 2: CHILD_SA (Negoziazione per le chiavi del traffico dati ESP)
# Diciamo a racoon come negoziare le chiavi quando il traffico corrisponde a queste LAN
sainfo address 192.168.2.0/24 any address 192.168.1.0/24 any {
    pfs_group 2;                        # Perfect Forward Secrecy
    encryption_algorithm 3des;          # Cifratura ESP (sui dati utente)
    authentication_algorithm hmac_md5;  # Integrità ESP
    compression_algorithm deflate;      # Opzionale: compressione payload
}