# File: r1/etc/ipsec-tools.conf
flush;
spdflush;

# SPD outgoing from lanA to lanB
spdadd 192.168.1.0/24 192.168.2.0/24 any -P out ipsec esp/tunnel/100.60.0.2-100.90.0.2/require;
# SPD incoming from lanB to lanA
spdadd 192.168.2.0/24 192.168.1.0/24 any -P in ipsec esp/tunnel/100.90.0.2-100.60.0.2/require;